# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8362046b9da3f99d1f3e6a4824f705d963e48cd99782fcaf9fde4a830aa7befdfca9665cbfa16a95e2c8df55524b54db2c54d58f0853e856db26bd8f8304c720

test:
  secret_key_base: 44921051cc2fe61cff3c773b0d81e33ba3dfdc8092703a4a2ec59efe002a38a85587ff15f7636e89782f10f2363237cefad3666dd2c4ad3e031723303019edc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
